package controller;

import domainlogic.BehaviorConductor;

public class ControllerManager {
	public BehaviorConductor bc;
	public NavbarController navbarCtr;
	public DisplayController displayCtr;
	public LoginController loginCtr;
	public LogoutController logoutCtr;
	public RegisterController registerCtr;
	public GetProfileController getProfileCtr;
	public EditProfileController editProfileCtr;
	public GetAllItemsController getAllItemsCtr;
	public GetItemByIdController getItemByIdCtr;
	public GetItemsBySellerIdController getItemsBySellerIdctr;
	public GetItemsByKeywordController getItemsByKeyCtr;
	public GetCartController getCartCtr;
	public AddToCartController addToCartCtr;
	public RemoveFromCartController removeFromCartCtr;
	public GetAddressesController getAddrsCtr;
	public AddAddressController addAddrCtr;
	public UpdateAddressController updateAddrCtr;
	public DeleteAddressController deleteAddrCtr;
	public ChargeBalanceController chargeBalanceCtr;
	public PurchaseController purchaseCtr;
	public AddItemController addItemCtr;
	public UpdateItemController updateItemCtr;
	public DeleteItemController deleteItemCtr;
	public GetOrdersController getOrdersCtr;
	public AddOrderController addOrderCtr;
	public DeleteOrderController deleteOrderCtr;
	public SendMessageController sendMsgCtr;
	public GetReceiveMessagesController getRecvMsgCtr;
	public GetSendMessagesController getSendMsgCtr;
	public DeleteMessageController deleteMsgCtr;
	public GetCommentsByItemIdController getCommentsByItemIdCtr;
	public GetCommentsByUserIdController getCommentsByUserIdCtr;
	public MakeCommentController makeCommentCtr;
	public DeleteCommentController deleteCommentCtr;
	
	public ControllerManager() {
		bc = new BehaviorConductor();
		navbarCtr = new NavbarController();
		displayCtr = new DisplayController();
		loginCtr = new LoginController();
		logoutCtr = new LogoutController();
		registerCtr = new RegisterController();
		getProfileCtr = new GetProfileController();
		editProfileCtr = new EditProfileController();
		getAllItemsCtr = new GetAllItemsController();
		getItemByIdCtr = new GetItemByIdController();
		getItemsBySellerIdctr = new GetItemsBySellerIdController();
		getItemsByKeyCtr = new GetItemsByKeywordController();
		getCartCtr = new GetCartController();
		addToCartCtr = new AddToCartController();
		removeFromCartCtr = new RemoveFromCartController();
		getAddrsCtr = new GetAddressesController();
		addAddrCtr = new AddAddressController();
		updateAddrCtr = new UpdateAddressController();
		deleteAddrCtr = new DeleteAddressController();
		chargeBalanceCtr = new ChargeBalanceController();
		purchaseCtr = new PurchaseController();
		addItemCtr = new AddItemController();
		updateItemCtr = new UpdateItemController();
		deleteItemCtr = new DeleteItemController();
		getOrdersCtr = new GetOrdersController();
		addOrderCtr = new AddOrderController();
		deleteOrderCtr = new DeleteOrderController();
		sendMsgCtr = new SendMessageController();
		getRecvMsgCtr = new GetReceiveMessagesController();
		getSendMsgCtr = new GetSendMessagesController();
		deleteMsgCtr = new DeleteMessageController();
		getCommentsByItemIdCtr = new GetCommentsByItemIdController();
		getCommentsByUserIdCtr = new GetCommentsByUserIdController();
		makeCommentCtr = new MakeCommentController();
		deleteCommentCtr = new DeleteCommentController();
		
		navbarCtr.initializeBehaviorConductor(bc);
		displayCtr.initializeBehaviorConductor(bc);
		loginCtr.initializeBehaviorConductor(bc);
		logoutCtr.initializeBehaviorConductor(bc);
		registerCtr.initializeBehaviorConductor(bc);
		getProfileCtr.initializeBehaviorConductor(bc);
		editProfileCtr.initializeBehaviorConductor(bc);
		getAllItemsCtr.initializeBehaviorConductor(bc);
		getItemByIdCtr.initializeBehaviorConductor(bc);
		getItemsBySellerIdctr.initializeBehaviorConductor(bc);
		getItemsByKeyCtr.initializeBehaviorConductor(bc);
		getCartCtr.initializeBehaviorConductor(bc);
		addToCartCtr.initializeBehaviorConductor(bc);
		removeFromCartCtr.initializeBehaviorConductor(bc);
		getAddrsCtr.initializeBehaviorConductor(bc);
		addAddrCtr.initializeBehaviorConductor(bc);
		updateAddrCtr.initializeBehaviorConductor(bc);
		deleteAddrCtr.initializeBehaviorConductor(bc);
		chargeBalanceCtr.initializeBehaviorConductor(bc);
		purchaseCtr.initializeBehaviorConductor(bc);
		addItemCtr.initializeBehaviorConductor(bc);
		updateItemCtr.initializeBehaviorConductor(bc);
		deleteItemCtr.initializeBehaviorConductor(bc);
		getOrdersCtr.initializeBehaviorConductor(bc);
		addOrderCtr.initializeBehaviorConductor(bc);
		deleteOrderCtr.initializeBehaviorConductor(bc);
		sendMsgCtr.initializeBehaviorConductor(bc);
		getRecvMsgCtr.initializeBehaviorConductor(bc);
		getSendMsgCtr.initializeBehaviorConductor(bc);
		deleteMsgCtr.initializeBehaviorConductor(bc);
		getCommentsByItemIdCtr.initializeBehaviorConductor(bc);
		getCommentsByUserIdCtr.initializeBehaviorConductor(bc);
		makeCommentCtr.initializeBehaviorConductor(bc);
		deleteCommentCtr.initializeBehaviorConductor(bc);
	}
}