/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2019-09-19 02:09:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class item_002dlist_002d1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1098736424000L));
    _jspx_dependants.put("jar:file:/C:/Users/Kevin/IdeaProjects/OnlineShop/src/main/webapp/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098675090000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <!-- Required meta tags-->\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("    <meta name=\"description\" content=\"au theme template\">\n");
      out.write("    <meta name=\"author\" content=\"Hau Nguyen\">\n");
      out.write("    <meta name=\"keywords\" content=\"au theme template\">\n");
      out.write("\n");
      out.write("    <!-- Title Page-->\n");
      out.write("    <title>Dashboard</title>\n");
      out.write("\n");
      out.write("    <!-- Fontfaces CSS-->\n");
      out.write("    <link href=\"css/font-face.css\" rel=\"stylesheet\" media=\"all\">\n");
      out.write("    <link href=\"vendor/font-awesome-4.7/css/font-awesome.min.css\" rel=\"stylesheet\" media=\"all\">\n");
      out.write("    <link href=\"vendor/font-awesome-5/css/fontawesome-all.min.css\" rel=\"stylesheet\" media=\"all\">\n");
      out.write("    <link href=\"vendor/mdi-font/css/material-design-iconic-font.min.css\" rel=\"stylesheet\" media=\"all\">\n");
      out.write("\n");
      out.write("    <!-- Bootstrap CSS-->\n");
      out.write("    <link href=\"vendor/bootstrap-4.1/bootstrap.min.css\" rel=\"stylesheet\" media=\"all\">\n");
      out.write("\n");
      out.write("    <!-- Vendor CSS-->\n");
      out.write("    <link href=\"vendor/animsition/animsition.min.css\" rel=\"stylesheet\" media=\"all\">\n");
      out.write("    <link href=\"vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css\" rel=\"stylesheet\" media=\"all\">\n");
      out.write("    <link href=\"vendor/wow/animate.css\" rel=\"stylesheet\" media=\"all\">\n");
      out.write("    <link href=\"vendor/css-hamburgers/hamburgers.min.css\" rel=\"stylesheet\" media=\"all\">\n");
      out.write("    <link href=\"vendor/slick/slick.css\" rel=\"stylesheet\" media=\"all\">\n");
      out.write("    <link href=\"vendor/select2/select2.min.css\" rel=\"stylesheet\" media=\"all\">\n");
      out.write("    <link href=\"vendor/perfect-scrollbar/perfect-scrollbar.css\" rel=\"stylesheet\" media=\"all\">\n");
      out.write("\n");
      out.write("    <!-- Main CSS-->\n");
      out.write("    <link href=\"css/theme.css\" rel=\"stylesheet\" media=\"all\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"animsition\">\n");
      out.write("<div class=\"page-wrapper\">\n");
      out.write("    <!-- HEADER MOBILE-->\n");
      out.write("    <header class=\"header-mobile d-block d-lg-none\">\n");
      out.write("        <div class=\"header-mobile__bar\">\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("                <div class=\"header-mobile-inner\">\n");
      out.write("                    <a class=\"logo\" href=\"HTML/index.html\">\n");
      out.write("                        <img src=\"images/icon/logo.png\" alt=\"CoolAdmin\" />\n");
      out.write("                    </a>\n");
      out.write("                    <button class=\"hamburger hamburger--slider\" type=\"button\">\n");
      out.write("                            <span class=\"hamburger-box\">\n");
      out.write("                                <span class=\"hamburger-inner\"></span>\n");
      out.write("                            </span>\n");
      out.write("                    </button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <nav class=\"navbar-mobile\">\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("                <ul class=\"navbar-mobile__list list-unstyled\">\n");
      out.write("                    <li class=\"has-sub\">\n");
      out.write("                        <a class=\"js-arrow\" href=\"#\">\n");
      out.write("                            <i class=\"fas fa-tachometer-alt\"></i>Dashboard</a>\n");
      out.write("                        <ul class=\"navbar-mobile-sub__list list-unstyled js-sub-list\">\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"HTML/index.html\">Dashboard 1</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"HTML/index2.html\">Dashboard 2</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"HTML/index3.html\">Dashboard 3</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"HTML/index4.html\">Dashboard 4</a>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"HTML/chart.html\">\n");
      out.write("                            <i class=\"fas fa-chart-bar\"></i>Charts</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"HTML/table.html\">\n");
      out.write("                            <i class=\"fas fa-table\"></i>Tables</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"HTML/form.html\">\n");
      out.write("                            <i class=\"far fa-check-square\"></i>Forms</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                            <i class=\"fas fa-calendar-alt\"></i>Calendar</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"HTML/map.html\">\n");
      out.write("                            <i class=\"fas fa-map-marker-alt\"></i>Maps</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"has-sub\">\n");
      out.write("                        <a class=\"js-arrow\" href=\"#\">\n");
      out.write("                            <i class=\"fas fa-copy\"></i>Pages</a>\n");
      out.write("                        <ul class=\"navbar-mobile-sub__list list-unstyled js-sub-list\">\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"HTML/login.html\">Login</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"HTML/register.html\">Register</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"HTML/forget-pass.html\">Forget Password</a>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"has-sub\">\n");
      out.write("                        <a class=\"js-arrow\" href=\"#\">\n");
      out.write("                            <i class=\"fas fa-desktop\"></i>UI Elements</a>\n");
      out.write("                        <ul class=\"navbar-mobile-sub__list list-unstyled js-sub-list\">\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"HTML/button.html\">Button</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"HTML/badge.html\">Badges</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"HTML/tab.html\">Tabs</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"HTML/card.html\">Cards</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"HTML/alert.html\">Alerts</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"HTML/progress-bar.html\">Progress Bars</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"HTML/modal.html\">Modals</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"HTML/switch.html\">Switchs</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"HTML/grid.html\">Grids</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"HTML/fontawesome.html\">Fontawesome Icon</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"HTML/typo.html\">Typography</a>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("    </header>\n");
      out.write("    <!-- END HEADER MOBILE-->\n");
      out.write("\n");
      out.write("    <!-- MENU SIDEBAR-->\n");
      out.write("    <aside class=\"menu-sidebar d-none d-lg-block\">\n");
      out.write("        <div class=\"logo\">\n");
      out.write("            <a href=\"#\">\n");
      out.write("                <img src=\"images/icon/logo.png\" alt=\"Cool Admin\" />\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"menu-sidebar__content js-scrollbar1\">\n");
      out.write("            <nav class=\"navbar-sidebar\">\n");
      out.write("                <ul class=\"list-unstyled navbar__list\">\n");
      out.write("                    <li class=\"active has-sub\">\n");
      out.write("                        <a class=\"js-arrow\" href=\"#\">\n");
      out.write("                            <i class=\"fas fa-tachometer-alt\"></i>Item management</a>\n");
      out.write("                        <ul class=\"list-unstyled navbar__sub-list js-sub-list\">\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"item-list.jsp\">Items Overview</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"add-item.jsp\">Add Item</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\">TBD</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\">TBD</a>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"HTML/chart.html\">\n");
      out.write("                            <i class=\"fas fa-chart-bar\"></i>Charts</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"addCategory\">\n");
      out.write("                            <i class=\"fas fa-table\"></i>Category List</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"form.jsp\">\n");
      out.write("                            <i class=\"far fa-check-square\"></i>Add Category</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                            <i class=\"fas fa-calendar-alt\"></i>Calendar</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                            <i class=\"fas fa-map-marker-alt\"></i>TBD</a>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                </ul>\n");
      out.write("            </nav>\n");
      out.write("        </div>\n");
      out.write("    </aside>\n");
      out.write("    <!-- END MENU SIDEBAR-->\n");
      out.write("\n");
      out.write("    <!-- PAGE CONTAINER-->\n");
      out.write("    <div class=\"page-container\">\n");
      out.write("        <!-- HEADER DESKTOP-->\n");
      out.write("        <header class=\"header-desktop\">\n");
      out.write("            <div class=\"section__content section__content--p30\">\n");
      out.write("                <div class=\"container-fluid\">\n");
      out.write("                    <div class=\"header-wrap\">\n");
      out.write("                        <form class=\"form-header\" action=\"\" method=\"POST\">\n");
      out.write("                            <input class=\"au-input au-input--xl\" type=\"text\" name=\"search\" placeholder=\"Search for datas &amp; reports...\" />\n");
      out.write("                            <button class=\"au-btn--submit\" type=\"submit\">\n");
      out.write("                                <i class=\"zmdi zmdi-search\"></i>\n");
      out.write("                            </button>\n");
      out.write("                        </form>\n");
      out.write("                        <div class=\"header-button\">\n");
      out.write("                            <div class=\"noti-wrap\">\n");
      out.write("                                <div class=\"noti__item js-item-menu\">\n");
      out.write("                                    <i class=\"zmdi zmdi-comment-more\"></i>\n");
      out.write("                                    <span class=\"quantity\">1</span>\n");
      out.write("                                    <div class=\"mess-dropdown js-dropdown\">\n");
      out.write("                                        <div class=\"mess__title\">\n");
      out.write("                                            <p>You have 2 news message</p>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"mess__item\">\n");
      out.write("                                            <div class=\"image img-cir img-40\">\n");
      out.write("                                                <img src=\"images/icon/avatar-06.jpg\" alt=\"Michelle Moreno\" />\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"content\">\n");
      out.write("                                                <h6>Michelle Moreno</h6>\n");
      out.write("                                                <p>Have sent a photo</p>\n");
      out.write("                                                <span class=\"time\">3 min ago</span>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"mess__item\">\n");
      out.write("                                            <div class=\"image img-cir img-40\">\n");
      out.write("                                                <img src=\"images/icon/avatar-04.jpg\" alt=\"Diane Myers\" />\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"content\">\n");
      out.write("                                                <h6>Diane Myers</h6>\n");
      out.write("                                                <p>You are now connected on message</p>\n");
      out.write("                                                <span class=\"time\">Yesterday</span>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"mess__footer\">\n");
      out.write("                                            <a href=\"#\">View all messages</a>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"noti__item js-item-menu\">\n");
      out.write("                                    <i class=\"zmdi zmdi-email\"></i>\n");
      out.write("                                    <span class=\"quantity\">1</span>\n");
      out.write("                                    <div class=\"email-dropdown js-dropdown\">\n");
      out.write("                                        <div class=\"email__title\">\n");
      out.write("                                            <p>You have 3 New Emails</p>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"email__item\">\n");
      out.write("                                            <div class=\"image img-cir img-40\">\n");
      out.write("                                                <img src=\"images/icon/avatar-06.jpg\" alt=\"Cynthia Harvey\" />\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"content\">\n");
      out.write("                                                <p>Meeting about new dashboard...</p>\n");
      out.write("                                                <span>Cynthia Harvey, 3 min ago</span>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"email__item\">\n");
      out.write("                                            <div class=\"image img-cir img-40\">\n");
      out.write("                                                <img src=\"images/icon/avatar-05.jpg\" alt=\"Cynthia Harvey\" />\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"content\">\n");
      out.write("                                                <p>Meeting about new dashboard...</p>\n");
      out.write("                                                <span>Cynthia Harvey, Yesterday</span>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"email__item\">\n");
      out.write("                                            <div class=\"image img-cir img-40\">\n");
      out.write("                                                <img src=\"images/icon/avatar-04.jpg\" alt=\"Cynthia Harvey\" />\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"content\">\n");
      out.write("                                                <p>Meeting about new dashboard...</p>\n");
      out.write("                                                <span>Cynthia Harvey, April 12,,2018</span>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"email__footer\">\n");
      out.write("                                            <a href=\"#\">See all emails</a>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"noti__item js-item-menu\">\n");
      out.write("                                    <i class=\"zmdi zmdi-notifications\"></i>\n");
      out.write("                                    <span class=\"quantity\">3</span>\n");
      out.write("                                    <div class=\"notifi-dropdown js-dropdown\">\n");
      out.write("                                        <div class=\"notifi__title\">\n");
      out.write("                                            <p>You have 3 Notifications</p>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"notifi__item\">\n");
      out.write("                                            <div class=\"bg-c1 img-cir img-40\">\n");
      out.write("                                                <i class=\"zmdi zmdi-email-open\"></i>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"content\">\n");
      out.write("                                                <p>You got a email notification</p>\n");
      out.write("                                                <span class=\"date\">April 12, 2018 06:50</span>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"notifi__item\">\n");
      out.write("                                            <div class=\"bg-c2 img-cir img-40\">\n");
      out.write("                                                <i class=\"zmdi zmdi-account-box\"></i>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"content\">\n");
      out.write("                                                <p>Your account has been blocked</p>\n");
      out.write("                                                <span class=\"date\">April 12, 2018 06:50</span>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"notifi__item\">\n");
      out.write("                                            <div class=\"bg-c3 img-cir img-40\">\n");
      out.write("                                                <i class=\"zmdi zmdi-file-text\"></i>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"content\">\n");
      out.write("                                                <p>You got a new file</p>\n");
      out.write("                                                <span class=\"date\">April 12, 2018 06:50</span>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"notifi__footer\">\n");
      out.write("                                            <a href=\"#\">All notifications</a>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"account-wrap\">\n");
      out.write("                                <div class=\"account-item clearfix js-item-menu\">\n");
      out.write("                                    <div class=\"image\">\n");
      out.write("                                        <img src=\"images/icon/avatar-01.jpg\" alt=\"John Doe\" />\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"content\">\n");
      out.write("                                        <a class=\"js-acc-btn\" href=\"#\">");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("</a>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"account-dropdown js-dropdown\">\n");
      out.write("                                        <div class=\"info clearfix\">\n");
      out.write("                                            <div class=\"image\">\n");
      out.write("                                                <a href=\"#\">\n");
      out.write("                                                    <img src=\"images/icon/avatar-01.jpg\" alt=\"John Doe\" />\n");
      out.write("                                                </a>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"content\">\n");
      out.write("                                                <h5 class=\"name\">\n");
      out.write("                                                    <a href=\"#\">");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("/a>\n");
      out.write("                                                </h5>\n");
      out.write("                                                <span class=\"email\"></span>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"account-dropdown__body\">\n");
      out.write("                                            <div class=\"account-dropdown__item\">\n");
      out.write("                                                <a href=\"#\">\n");
      out.write("                                                    <i class=\"zmdi zmdi-account\"></i>Account</a>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"account-dropdown__item\">\n");
      out.write("                                                <a href=\"#\">\n");
      out.write("                                                    <i class=\"zmdi zmdi-settings\"></i>Setting</a>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"account-dropdown__item\">\n");
      out.write("                                                <a href=\"#\">\n");
      out.write("                                                    <i class=\"zmdi zmdi-money-box\"></i>Billing</a>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"account-dropdown__footer\">\n");
      out.write("                                            <a href=\"#\">\n");
      out.write("                                                <i class=\"zmdi zmdi-power\"></i>Logout</a>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </header>\n");
      out.write("        <!-- HEADER DESKTOP-->\n");
      out.write("\n");
      out.write("        <!-- MAIN CONTENT-->\n");
      out.write("        <div class=\"main-content\">\n");
      out.write("            <div class=\"section__content section__content--p30\">\n");
      out.write("                <div class=\"container-fluid\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-lg-9\">\n");
      out.write("                            <div class=\"table-responsive table--no-card m-b-30\">\n");
      out.write("                                <table class=\"table table-borderless table-striped table-earning\">\n");
      out.write("                                    <thead>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <th>count</th>\n");
      out.write("                                        <th>Item Name</th>\n");
      out.write("                                        <th>Item Category</th>\n");
      out.write("                                        <th>Price</th>\n");
      out.write("                                        <th>Stock</th>\n");
      out.write("\n");
      out.write("                                    </tr>\n");
      out.write("                                    </thead>\n");
      out.write("                                    <tbody>\n");
      out.write("                                    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                                    </tbody>\n");
      out.write("                                </table>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-md-12\">\n");
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- END MAIN CONTENT-->\n");
      out.write("            <!-- END PAGE CONTAINER-->\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Jquery JS-->\n");
      out.write("    <script src=\"vendor/jquery-3.2.1.min.js\"></script>\n");
      out.write("    <!-- Bootstrap JS-->\n");
      out.write("    <script src=\"vendor/bootstrap-4.1/popper.min.js\"></script>\n");
      out.write("    <script src=\"vendor/bootstrap-4.1/bootstrap.min.js\"></script>\n");
      out.write("    <!-- Vendor JS       -->\n");
      out.write("    <script src=\"vendor/slick/slick.min.js\">\n");
      out.write("    </script>\n");
      out.write("    <script src=\"vendor/wow/wow.min.js\"></script>\n");
      out.write("    <script src=\"vendor/animsition/animsition.min.js\"></script>\n");
      out.write("    <script src=\"vendor/bootstrap-progressbar/bootstrap-progressbar.min.js\">\n");
      out.write("    </script>\n");
      out.write("    <script src=\"vendor/counter-up/jquery.waypoints.min.js\"></script>\n");
      out.write("    <script src=\"vendor/counter-up/jquery.counterup.min.js\">\n");
      out.write("    </script>\n");
      out.write("    <script src=\"vendor/circle-progress/circle-progress.min.js\"></script>\n");
      out.write("    <script src=\"vendor/perfect-scrollbar/perfect-scrollbar.js\"></script>\n");
      out.write("    <script src=\"vendor/chartjs/Chart.bundle.min.js\"></script>\n");
      out.write("    <script src=\"vendor/select2/select2.min.js\">\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("    <!-- Main JS-->\n");
      out.write("    <script src=\"js/main.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
      out.write("<!-- end document-->\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /item-list-1.jsp(353,71) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.user}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                            ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /item-list-1.jsp(366,64) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.user}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                                            ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\n");
          out.write("                                                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /item-list-1.jsp(420,36) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.itemList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /item-list-1.jsp(420,36) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      // /item-list-1.jsp(420,36) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("s");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                                        <tr>\n");
            out.write("                                            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.stock}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                        </tr>\n");
            out.write("                                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
