/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2019-09-19 04:02:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class update_002ditem_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1098736424000L));
    _jspx_dependants.put("jar:file:/C:/Users/Kevin/IdeaProjects/OnlineShop/src/main/webapp/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098675090000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <!-- Required meta tags-->\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"au theme template\">\r\n");
      out.write("    <meta name=\"author\" content=\"Hau Nguyen\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"au theme template\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Title Page-->\r\n");
      out.write("    <title>Dashboard</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Fontfaces CSS-->\r\n");
      out.write("    <link href=\"css/font-face.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("    <link href=\"vendor/font-awesome-4.7/css/font-awesome.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("    <link href=\"vendor/font-awesome-5/css/fontawesome-all.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("    <link href=\"vendor/mdi-font/css/material-design-iconic-font.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS-->\r\n");
      out.write("    <link href=\"vendor/bootstrap-4.1/bootstrap.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Vendor CSS-->\r\n");
      out.write("    <link href=\"vendor/animsition/animsition.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("    <link href=\"vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("    <link href=\"vendor/wow/animate.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("    <link href=\"vendor/css-hamburgers/hamburgers.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("    <link href=\"vendor/slick/slick.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("    <link href=\"vendor/select2/select2.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("    <link href=\"vendor/perfect-scrollbar/perfect-scrollbar.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Main CSS-->\r\n");
      out.write("    <link href=\"css/theme.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"animsition\">\r\n");
      out.write("<div class=\"page-wrapper\">\r\n");
      out.write("    <!-- HEADER MOBILE-->\r\n");
      out.write("    <header class=\"header-mobile d-block d-lg-none\">\r\n");
      out.write("        <div class=\"header-mobile__bar\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <div class=\"header-mobile-inner\">\r\n");
      out.write("                    <a class=\"logo\" href=\"HTML/index.html\">\r\n");
      out.write("                        <img src=\"images/icon/logo.png\" alt=\"CoolAdmin\" />\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <button class=\"hamburger hamburger--slider\" type=\"button\">\r\n");
      out.write("                            <span class=\"hamburger-box\">\r\n");
      out.write("                                <span class=\"hamburger-inner\"></span>\r\n");
      out.write("                            </span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"navbar-mobile\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <ul class=\"navbar-mobile__list list-unstyled\">\r\n");
      out.write("                    <li class=\"has-sub\">\r\n");
      out.write("                        <a class=\"js-arrow\" href=\"#\">\r\n");
      out.write("                            <i class=\"fas fa-tachometer-alt\"></i>Dashboard</a>\r\n");
      out.write("                        <ul class=\"navbar-mobile-sub__list list-unstyled js-sub-list\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"HTML/index.html\">Dashboard 1</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"HTML/index2.html\">Dashboard 2</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"HTML/index3.html\">Dashboard 3</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"HTML/index4.html\">Dashboard 4</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"HTML/chart.html\">\r\n");
      out.write("                            <i class=\"fas fa-chart-bar\"></i>Charts</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"HTML/table.html\">\r\n");
      out.write("                            <i class=\"fas fa-table\"></i>Tables</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"HTML/form.html\">\r\n");
      out.write("                            <i class=\"far fa-check-square\"></i>Forms</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <i class=\"fas fa-calendar-alt\"></i>Calendar</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"HTML/map.html\">\r\n");
      out.write("                            <i class=\"fas fa-map-marker-alt\"></i>Maps</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"has-sub\">\r\n");
      out.write("                        <a class=\"js-arrow\" href=\"#\">\r\n");
      out.write("                            <i class=\"fas fa-copy\"></i>Pages</a>\r\n");
      out.write("                        <ul class=\"navbar-mobile-sub__list list-unstyled js-sub-list\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"HTML/login.html\">Login</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"HTML/register.html\">Register</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"HTML/forget-pass.html\">Forget Password</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"has-sub\">\r\n");
      out.write("                        <a class=\"js-arrow\" href=\"#\">\r\n");
      out.write("                            <i class=\"fas fa-desktop\"></i>UI Elements</a>\r\n");
      out.write("                        <ul class=\"navbar-mobile-sub__list list-unstyled js-sub-list\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"HTML/button.html\">Button</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"HTML/badge.html\">Badges</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"HTML/tab.html\">Tabs</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"HTML/card.html\">Cards</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"HTML/alert.html\">Alerts</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"HTML/progress-bar.html\">Progress Bars</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"HTML/modal.html\">Modals</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"HTML/switch.html\">Switchs</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"HTML/grid.html\">Grids</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"HTML/fontawesome.html\">Fontawesome Icon</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"HTML/typo.html\">Typography</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- END HEADER MOBILE-->\r\n");
      out.write("\r\n");
      out.write("    <!-- MENU SIDEBAR-->\r\n");
      out.write("    <aside class=\"menu-sidebar d-none d-lg-block\">\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("                <img src=\"images/icon/logo.png\" alt=\"Cool Admin\" />\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"menu-sidebar__content js-scrollbar1\">\r\n");
      out.write("            <nav class=\"navbar-sidebar\">\r\n");
      out.write("                <ul class=\"list-unstyled navbar__list\">\r\n");
      out.write("                    <li class=\"active has-sub\">\r\n");
      out.write("                        <a class=\"js-arrow\" href=\"#\">\r\n");
      out.write("                            <i class=\"fas fa-tachometer-alt\"></i>Item management</a>\r\n");
      out.write("                        <ul class=\"list-unstyled navbar__sub-list js-sub-list\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"getItems\">Items Overview</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"add-item.jsp\">Add Item</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">TBD</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">TBD</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <i class=\"fas fa-chart-bar\"></i>TBD</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"addCategory\">\r\n");
      out.write("                            <i class=\"fas fa-table\"></i>Category List</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"form.jsp\">\r\n");
      out.write("                            <i class=\"far fa-check-square\"></i>Add Category</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <i class=\"fas fa-calendar-alt\"></i>TBD</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <i class=\"fas fa-map-marker-alt\"></i>TBD</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("    </aside>\r\n");
      out.write("    <!-- END MENU SIDEBAR-->\r\n");
      out.write("\r\n");
      out.write("    <!-- PAGE CONTAINER-->\r\n");
      out.write("    <div class=\"page-container\">\r\n");
      out.write("        <!-- HEADER DESKTOP-->\r\n");
      out.write("        <header class=\"header-desktop\">\r\n");
      out.write("            <div class=\"section__content section__content--p30\">\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("                    <div class=\"header-wrap\">\r\n");
      out.write("                        <form class=\"form-header\" action=\"\" method=\"POST\">\r\n");
      out.write("                            <input class=\"au-input au-input--xl\" type=\"text\" name=\"search\" placeholder=\"Search for datas &amp; reports...\" />\r\n");
      out.write("                            <button class=\"au-btn--submit\" type=\"submit\">\r\n");
      out.write("                                <i class=\"zmdi zmdi-search\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <div class=\"header-button\">\r\n");
      out.write("                            <div class=\"noti-wrap\">\r\n");
      out.write("                                <div class=\"noti__item js-item-menu\">\r\n");
      out.write("                                    <i class=\"zmdi zmdi-comment-more\"></i>\r\n");
      out.write("                                    <span class=\"quantity\">1</span>\r\n");
      out.write("                                    <div class=\"mess-dropdown js-dropdown\">\r\n");
      out.write("                                        <div class=\"mess__title\">\r\n");
      out.write("                                            <p>You have 2 news message</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"mess__item\">\r\n");
      out.write("                                            <div class=\"image img-cir img-40\">\r\n");
      out.write("                                                <img src=\"images/icon/avatar-06.jpg\" alt=\"Michelle Moreno\" />\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"content\">\r\n");
      out.write("                                                <h6>Michelle Moreno</h6>\r\n");
      out.write("                                                <p>Have sent a photo</p>\r\n");
      out.write("                                                <span class=\"time\">3 min ago</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"mess__item\">\r\n");
      out.write("                                            <div class=\"image img-cir img-40\">\r\n");
      out.write("                                                <img src=\"images/icon/avatar-04.jpg\" alt=\"Diane Myers\" />\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"content\">\r\n");
      out.write("                                                <h6>Diane Myers</h6>\r\n");
      out.write("                                                <p>You are now connected on message</p>\r\n");
      out.write("                                                <span class=\"time\">Yesterday</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"mess__footer\">\r\n");
      out.write("                                            <a href=\"#\">View all messages</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"noti__item js-item-menu\">\r\n");
      out.write("                                    <i class=\"zmdi zmdi-email\"></i>\r\n");
      out.write("                                    <span class=\"quantity\">1</span>\r\n");
      out.write("                                    <div class=\"email-dropdown js-dropdown\">\r\n");
      out.write("                                        <div class=\"email__title\">\r\n");
      out.write("                                            <p>You have 3 New Emails</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"email__item\">\r\n");
      out.write("                                            <div class=\"image img-cir img-40\">\r\n");
      out.write("                                                <img src=\"images/icon/avatar-06.jpg\" alt=\"Cynthia Harvey\" />\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"content\">\r\n");
      out.write("                                                <p>Meeting about new dashboard...</p>\r\n");
      out.write("                                                <span>Cynthia Harvey, 3 min ago</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"email__item\">\r\n");
      out.write("                                            <div class=\"image img-cir img-40\">\r\n");
      out.write("                                                <img src=\"images/icon/avatar-05.jpg\" alt=\"Cynthia Harvey\" />\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"content\">\r\n");
      out.write("                                                <p>Meeting about new dashboard...</p>\r\n");
      out.write("                                                <span>Cynthia Harvey, Yesterday</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"email__item\">\r\n");
      out.write("                                            <div class=\"image img-cir img-40\">\r\n");
      out.write("                                                <img src=\"images/icon/avatar-04.jpg\" alt=\"Cynthia Harvey\" />\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"content\">\r\n");
      out.write("                                                <p>Meeting about new dashboard...</p>\r\n");
      out.write("                                                <span>Cynthia Harvey, April 12,,2018</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"email__footer\">\r\n");
      out.write("                                            <a href=\"#\">See all emails</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"noti__item js-item-menu\">\r\n");
      out.write("                                    <i class=\"zmdi zmdi-notifications\"></i>\r\n");
      out.write("                                    <span class=\"quantity\">3</span>\r\n");
      out.write("                                    <div class=\"notifi-dropdown js-dropdown\">\r\n");
      out.write("                                        <div class=\"notifi__title\">\r\n");
      out.write("                                            <p>You have 3 Notifications</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"notifi__item\">\r\n");
      out.write("                                            <div class=\"bg-c1 img-cir img-40\">\r\n");
      out.write("                                                <i class=\"zmdi zmdi-email-open\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"content\">\r\n");
      out.write("                                                <p>You got a email notification</p>\r\n");
      out.write("                                                <span class=\"date\">April 12, 2018 06:50</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"notifi__item\">\r\n");
      out.write("                                            <div class=\"bg-c2 img-cir img-40\">\r\n");
      out.write("                                                <i class=\"zmdi zmdi-account-box\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"content\">\r\n");
      out.write("                                                <p>Your account has been blocked</p>\r\n");
      out.write("                                                <span class=\"date\">April 12, 2018 06:50</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"notifi__item\">\r\n");
      out.write("                                            <div class=\"bg-c3 img-cir img-40\">\r\n");
      out.write("                                                <i class=\"zmdi zmdi-file-text\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"content\">\r\n");
      out.write("                                                <p>You got a new file</p>\r\n");
      out.write("                                                <span class=\"date\">April 12, 2018 06:50</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"notifi__footer\">\r\n");
      out.write("                                            <a href=\"#\">All notifications</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"account-wrap\">\r\n");
      out.write("                                <div class=\"account-item clearfix js-item-menu\">\r\n");
      out.write("                                    <div class=\"image\">\r\n");
      out.write("                                        <img src=\"images/icon/avatar-01.jpg\" alt=\"John Doe\" />\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"content\">\r\n");
      out.write("                                        <a class=\"js-acc-btn\" href=\"#\">");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"account-dropdown js-dropdown\">\r\n");
      out.write("                                        <div class=\"info clearfix\">\r\n");
      out.write("                                            <div class=\"image\">\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <img src=\"images/icon/avatar-01.jpg\" alt=\"John Doe\" />\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"content\">\r\n");
      out.write("                                                <h5 class=\"name\">\r\n");
      out.write("                                                    <a href=\"#\">");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("</a>\r\n");
      out.write("                                                </h5>\r\n");
      out.write("                                                <span class=\"email\">");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"account-dropdown__body\">\r\n");
      out.write("                                            <div class=\"account-dropdown__item\">\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <i class=\"zmdi zmdi-account\"></i>Account</a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"account-dropdown__item\">\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <i class=\"zmdi zmdi-settings\"></i>Setting</a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"account-dropdown__item\">\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <i class=\"zmdi zmdi-money-box\"></i>Billing</a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"account-dropdown__footer\">\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <i class=\"zmdi zmdi-power\"></i>Logout</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <!-- HEADER DESKTOP-->\r\n");
      out.write("\r\n");
      out.write("        <!-- MAIN CONTENT-->\r\n");
      out.write("        <div class=\"main-content\">\r\n");
      out.write("            <div class=\"section__content section__content--p30\">\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-6\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <div class=\"card-header\">\r\n");
      out.write("                                    <strong>Add</strong> Item\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-body card-block\">\r\n");
      out.write("                                    <form action=\"item-update-process.jsp\" method=\"post\"  class=\"form-horizontal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type = \"hidden\" name = \"id\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("                                        <div class=\"row form-group\">\r\n");
      out.write("                                            <div class=\"col col-md-3\">\r\n");
      out.write("                                                <label for=\"text-input\" class=\" form-control-label\">Name</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-12 col-md-9\">\r\n");
      out.write("                                                <input type=\"text\" id=\"text-input\" name=\"name\" placeholder=\"name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"form-control\">\r\n");
      out.write("                                                <small class=\"form-text text-muted\">Add a item name</small>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"row form-group\">\r\n");
      out.write("                                            <div class=\"col col-md-3\">\r\n");
      out.write("                                                <label for=\"password-input\" class=\" form-control-label\">Price</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-12 col-md-9\">\r\n");
      out.write("                                                <input type=\"text\" id=\"password-input\" name=\"price\" placeholder=\"price\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"form-control\">\r\n");
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"row form-group\">\r\n");
      out.write("                                            <div class=\"col col-md-3\">\r\n");
      out.write("                                                <label for=\"password-input\" class=\" form-control-label\">Stock</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-12 col-md-9\">\r\n");
      out.write("                                                <input type=\"text\" id=\"stock\" name=\"stock\" placeholder=\"stock\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.stock}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"form-control\">\r\n");
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"row form-group\">\r\n");
      out.write("                                            <div class=\"col col-md-3\">\r\n");
      out.write("                                                <label for=\"textarea-input\" class=\" form-control-label\">Description</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-12 col-md-9\">\r\n");
      out.write("                                                <textarea name=\"description\" id=\"textarea-input\" rows=\"9\" placeholder=\"Content...\" class=\"form-control\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"row form-group\">\r\n");
      out.write("                                            <div class=\"col col-md-3\">\r\n");
      out.write("                                                <label for=\"select\" class=\" form-control-label\">Category</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-12 col-md-9\">\r\n");
      out.write("                                                <select name=\"category\" id=\"category\" class=\"form-control\">\r\n");
      out.write("                                                    <option value=\"clothes\">clothes</option>\r\n");
      out.write("                                                    <option value=\"food\">food</option>\r\n");
      out.write("                                                    <option value=\"e-product\">e-product</option>\r\n");
      out.write("                                                </select>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-footer\">\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-primary btn-sm\">\r\n");
      out.write("                                        <i class=\"fa fa-dot-circle-o\"></i> Submit\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                    <button type=\"reset\" class=\"btn btn-danger btn-sm\">\r\n");
      out.write("                                        <i class=\"fa fa-ban\"></i> Reset\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-12\">\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- END MAIN CONTENT-->\r\n");
      out.write("        <!-- END PAGE CONTAINER-->\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Jquery JS-->\r\n");
      out.write("<script src=\"vendor/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<!-- Bootstrap JS-->\r\n");
      out.write("<script src=\"vendor/bootstrap-4.1/popper.min.js\"></script>\r\n");
      out.write("<script src=\"vendor/bootstrap-4.1/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- Vendor JS       -->\r\n");
      out.write("<script src=\"vendor/slick/slick.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"vendor/wow/wow.min.js\"></script>\r\n");
      out.write("<script src=\"vendor/animsition/animsition.min.js\"></script>\r\n");
      out.write("<script src=\"vendor/bootstrap-progressbar/bootstrap-progressbar.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"vendor/counter-up/jquery.waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"vendor/counter-up/jquery.counterup.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"vendor/circle-progress/circle-progress.min.js\"></script>\r\n");
      out.write("<script src=\"vendor/perfect-scrollbar/perfect-scrollbar.js\"></script>\r\n");
      out.write("<script src=\"vendor/chartjs/Chart.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"vendor/select2/select2.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Main JS-->\r\n");
      out.write("<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("<!-- end document-->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /update-item.jsp(354,71) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.user}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                            ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /update-item.jsp(367,64) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.user}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                                        ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("                                                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /update-item.jsp(371,68) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.user}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                                    ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.phoneNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("                                                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
